config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :tasks
  end

  root 'projects#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Project < ApplicationRecord
  # Associations
  has_many :tasks, dependent: :destroy

  # Validations
  validates :title, presence: true
end

app/models/task.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: tasks
#
#  id               :integer          not null, primary key
#  project_id       :integer          not null
#  assigned_user_id :integer          not null
#  title            :string
#  description      :text
#  story_points     :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Task < ApplicationRecord
  # Enums
  enum status: {
    unstarted: 0,
    on_hold: 1,
    in_progress: 2,
    code_review: 3,
    internal_review: 4,
    client_review: 5,
    ready_for_live: 6,
    done: 7
  }

  # Associations
  belongs_to :project
  belongs_to :assigned_user, class_name: 'User'

  # Validations
  validates :title, :description, :story_points, :status, presence: true
  validates :story_points, numericality: { greater_than_or_equal_to: 0 }

  # Callbacks
  after_commit TaskCallbacks

  # Methods
  def broadcast_task_update
    broadcast_update_to "project_tasks_#{project.id}",
                        partial: 'tasks/task',
                        locals: { task: self },
                        target: "task_#{id}"
  end

  def broadcast_board_update
    board_component = BoardComponent.new(tasks: project.tasks)

    broadcast_update_to "project_tasks_#{project.id}",
                        html: ApplicationController.render(board_component),
                        target: "board_#{project.id}"
  end
end

app/models/task_callbacks.rb
# frozen_string_literal: true

class TaskCallbacks
  def self.after_commit(task)
    is_newly_created = task.saved_change_to_id?

    if task.saved_change_to_status? || task.saved_change_to_story_points? || is_newly_created
      task.broadcast_board_update
    else
      task.broadcast_task_update
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Associations
  has_many :tasks,
           foreign_key: :assigned_user_id,
           class_name: 'Task',
           dependent: :destroy,
           inverse_of: :assigned_user

  # Macros
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[show edit update destroy]

  def index
    @projects = Project.all
  end

  def show
    redirect_to project_tasks_url(@project)
  end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: t('.successfully.created') }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: t('.successfully.updated') }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: t('.successfully.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = @project.tasks
  end

  def show
    redirect_to project_tasks_url(@project)
  end

  def new
    @task = @project.tasks.build
  end

  def edit; end

  def create
    @task = @project.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_task_url(@project, @task), notice: t('.successfully.created') }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_task_url(@project, @task), notice: t('.successfully.updated') }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to project_tasks_url(@project), notice: t('.successfully.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:assigned_user_id, :title, :description, :story_points, :status)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Taskany
    meta name="viewport" content="width=device-width,initial-scale=1"
    == csrf_meta_tags
    == csp_meta_tag

    == stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbo-track': 'reload'
    == stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    == javascript_importmap_tags

  body class="p-2"
    - if flash[:notice].present?
      p = flash[:notice]
    - if flash[:alert].present?
      p = flash[:alert]

    == yield

app/views/projects/_form.html.slim
== form_with(model: project) do |form|

  div class="flex gap-2"
    == form.text_field :title, required: true, class: 'rounded-lg border border-cyan-300 p-2'

    == form.submit 'Save', class: 'rounded-lg bg-yellow-300 text-center px-4 py-2 cursor-pointer shadow-md hover:bg-yellow-400'

  - if project.errors.any?
    div class="text-red-500"
      ul
        - project.errors.each do |error|
          li = error.full_message

app/views/projects/_project.html.slim
== turbo_frame_tag project
  div class="flex"
    h1 class="font-bold text-xl"
      = project.title
    == link_to '✏️', edit_project_path(project)

app/views/projects/edit.html.slim
h1 class="font-bold text-xl mb-4" Edit project

== turbo_frame_tag @project, target: '_top' do
  div class="flex gap-1 items-start"
    == render 'form', project: @project
    == link_to 'Cancel',
            project_tasks_path(@project),
            class: 'rounded-lg border border-cyan-300 text-center px-4 py-2 shadow-md hover:bg-cyan-100'

app/views/projects/index.html.slim
h1 class="font-bold text-xl mb-4" Projects

div class="inline-flex flex-col gap-2"
  == link_to 'New project',
          new_project_path,
          class: 'rounded-lg bg-yellow-300 text-center px-4 py-2 cursor-pointer shadow-md hover:bg-yellow-400 mb-2'

  - @projects.each do |project|
    == link_to project.title,
            project_tasks_path(project),
            class: 'rounded-lg border border-cyan-300 text-center px-4 py-2 shadow-md hover:bg-cyan-100'

app/views/projects/new.html.slim
h1 class="font-bold text-xl mb-4" New project

div class="flex flex-col gap-2 items-start"
  == render 'form', project: @project

  == link_to 'Back to projects',
          projects_path,
          class: 'rounded-lg border border-cyan-300 text-center px-4 py-2 shadow-md hover:bg-cyan-100'

app/views/tasks/_form.html.slim
== form_with(model: [@project, task], html: { class: 'flex flex-col' }) do |form|
  - if task.errors.any?
    div class="text-red-500 bg-cyan-100 p-2 mb-1 rounded-lg"
      h2 = pluralize(task.errors.count, 'error') + ' prohibited this task from being saved:'
      ul
        - task.errors.each do |error|
          li = '- ' + error.full_message

  == form.label :title
  == form.text_field :title, required: true, class: 'mb-1 rounded-lg border-none p-2'

  == form.label :description
  == form.text_area :description, required: true, class: 'mb-1 rounded-lg border-none p-2', rows: 4

  == form.label :story_points
  == form.number_field :story_points, required: true, class: 'mb-1 rounded-lg border-none p-2'

  == form.label :assigned_user_id
  == form.collection_select :assigned_user_id, User.all, :id, :email, {},
          class: 'mb-1 rounded-lg border-none p-2'

  == form.label :status
  == form.select :status, Task.statuses.keys.map { |s| [s.humanize, s] }, {},
          class: 'mb-2 rounded-lg border-none p-2'

  == form.submit class: 'rounded-lg bg-yellow-300 text-center p-2 cursor-pointer shadow-md hover:bg-yellow-400 mb-1'

app/views/tasks/_task.html.slim
== turbo_frame_tag task do
  article id="#{dom_id task}" class="bg-cyan-300 p-2 rounded-lg flex flex-col gap-1 shadow-md border border-cyan-400"
    div class="flex justify-between gap-2"
      p class="font-bold truncate text-ellipsis"
        = task.title
      h4
        = task.story_points

    p class="truncate text-ellipsis"
      = task.description

    div class="flex justify-between gap-2"
      p class="italic truncate text-ellipsis"
        = task.assigned_user&.email || 'unknown'
      == link_to '✏️', edit_project_task_path(task.project, task)

app/views/tasks/edit.html.slim
h1 class="font-bold text-xl mb-4" Edit task

div class="max-w-xl"
  == turbo_frame_tag @task, target: '_top' do
    article class="bg-cyan-300 p-2 rounded-lg flex flex-col gap-1 shadow-inner border border-cyan-400"
      == render 'form', task: @task
      == link_to 'Cancel',
              project_tasks_path(@task.project),
              class: 'rounded-lg border border-cyan-500 text-center p-2 shadow-md hover:bg-cyan-400'

app/views/tasks/index.html.slim
== turbo_stream_from "project_tasks_#{@project.id}"

div class="flex justify-between items-start mb-2"
  == render @project
  == link_to 'All projects',
          projects_path,
          class: 'rounded-lg border border-cyan-300 text-center px-4 py-2 shadow-md hover:bg-cyan-100'

== turbo_frame_tag "new_task_#{@project.id}"
  == link_to 'New task',
          new_project_task_path(@project),
          class: 'inline-block rounded-lg bg-yellow-300 text-center px-4 py-2 cursor-pointer shadow-md hover:bg-yellow-400 mb-2'

== turbo_frame_tag "board_#{@project.id}" do
  == render(BoardComponent.new(tasks: @tasks))

app/views/tasks/new.html.slim
h1 class="font-bold text-xl mb-4" New task

== turbo_frame_tag "new_task_#{@project.id}", target: '_top'
  article class="max-w-xl bg-cyan-300 p-2 rounded-lg flex flex-col gap-1 shadow-inner border border-cyan-400 mb-2"
    == render 'form', task: @task
    == link_to 'Cancel',
            project_tasks_path(@task.project),
            class: 'rounded-lg border border-cyan-500 text-center p-2 shadow-md hover:bg-cyan-400'